# cf. https://pre-commit.com/#plugins

repos:
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        # cf. https://commitlint.js.org/#/reference-cli
        # cf. https://github.com/conventional-changelog/commitlint#config
        entry: pnpm commitlint
        args:
          - --strict
          - --edit
        language: system
        # Run `(poetry run) pre-commit install --hook-type commit-msg` beforehand.
        # cf. https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
        stages: [commit-msg]
