# cf. https://docs.astral.sh/ruff/configuration
# cf. https://docs.astral.sh/ruff/settings

# cf. https://docs.astral.sh/ruff/settings/#lint_select
# cf. https://docs.astral.sh/ruff/rules
select = [
  "ANN", # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
  "F",   # https://docs.astral.sh/ruff/rules/#pyflakes-f
  "E",   # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
  "W",   # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
  "C90", # https://docs.astral.sh/ruff/rules/#mccabe-c90
]
